config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :registrations
  resources :events
  resource :session
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'home_page#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true

  belongs_to :user
  belongs_to :event

end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :date, presence: true
  validates :location, presence: true
  validates :state, presence: true

  validate :validate_future_date_event

  belongs_to :user
  has_many :registrations, dependent: :destroy
  has_many :joined_users, through: :registrations, source: :user
  has_many :comments, dependent: :destroy
  has_many :user_comment, through: :comments, source: :user


  def validate_future_date_event
    if date.present? && date < Date.today
      errors.add(:date, "Event date must be in future")
    end
  end

  def self.find_same_state(state)
    Event.where( "state = ?", state )
  end

  def self.find_not_same_state(state)
    Event.where.not("state = ?", state)
  end
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :location, presence: true
  validates :state, presence: true
  validates :email, presence: true,
            format: /\A\S+@\S+\z/,
            uniqueness: {case_sensitive: false}

  has_many :events, dependent: :destroy
  has_many :registrations, dependent: :destroy
  has_many :joined_events, through: :registrations, source: :event
  has_many :comments, dependent: :destroy
  has_many :event_comment, through: :comments, source: :event

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    event_id=params[:event_id]
    @comment = Comment.new(:user_id => session[:user_id], :event_id => event_id, :comment => params[:comment])
    @comment.save
    redirect_to url_for(:controller => :events, :action => :show, :id => event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events_same_state = Event.find_same_state(find_session_user.state)
    @events_not_same_state = Event.find_not_same_state(find_session_user.state)

    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = User.find(session[:user_id])
    if !@event.save
      error_message
    end
    redirect_to index
  end

  def show
    @event = Event.find(params[:id])
    @joined_users = @event.joined_users
    @comment_string = event_comments
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to index
  end
  private
  def event_params
    params.require(:event).permit(:name, :date, :location, :state)
  end

  def error_message
    flash[:event] = @event
    flash[:error] = true
    flash[:error_count] = @event.errors.count
    flash[:full_error_messages] = @event.errors.full_messages
  end

  def find_session_user
    User.find(session[:user_id])
  end

  def event_comments
    comment_string=""
    @event.comments.each do |comment|
      comment_string += comment.user.first_name + " says: " + comment.comment + "\n"
      comment_string += "---------------------------\n"
    end
    comment_string
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
    @user = User.new
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    Registration.new(:user_id => session[:user_id], :event_id => params[:event_id]).save
    redirect_to url_for(:controller => :events, :action => :index)
  end

  def destroy
    @registration = Registration.find(params[:id])
    @registration.destroy
    redirect_to url_for(:controller => :events, :action => :index)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash[:error] = true
      flash[:error_count] = 1
      flash[:full_error_messages] = ["Invalid email/password!"]
      redirect_to url_for(:controller => :home_page, :action => :index)
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks"
    else
      error_message
      redirect_to url_for(:controller => :home_page, :action => :index)
    end
  end

  def update
    @user = User.find(params[:id])
    if !@user.update(user_params)
      error_message
    end
    redirect_to url_for(:controller => :events, :action => :index)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :location, :state, :password, :password_confirmation)
  end

  def error_message
    flash[:user] = @user
    flash[:error] = true
    flash[:error_count] = @user.errors.count
    flash[:full_error_messages] = @user.errors.full_messages
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    end
  end

  def is_user_joined_event?(user_id, event_id)
    Registration.find_by(user_id:user_id, event_id:event_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Here are some of events at your state</h1>
<table id="events_same_state">
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Location</th>
    <th>Host</th>
    <th>Action/Status</th>
  <tr>
    <% @events_same_state.each do |event| %>
      <tr>
        <td><%= link_to event.name, event %></td>
        <td><%= event.date %></td>
        <td><%= event.location %></td>
        <td><%= event.user.first_name %></td>
        <td>
          <% if event.user.id == session[:user_id] %>
              <%= link_to "Edit", event %>
              <%= link_to "Delete", event, method: :delete %>
          <% else %>
              <% if is_user_joined_event? event.id, session[:user_id] %>
                  Joining
                  <%= link_to "Cancel", is_user_joined_event?(event.id, session[:user_id]), method: :delete %>
              <% else %>
                  <%= link_to "Join", {:controller => "registrations", :action => "new", :event_id => event.id} %>
              <% end %>
          <% end %>
        </td>
      </tr>
  <% end %>
</table>
<h1>Here are some of events not at your state</h1>
<table id="events_not_same_state">
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Location</th>
    <th>State</th>
    <th>Host</th>
    <th>Action/Status</th>
  <tr>
    <% @events_not_same_state.each do |event| %>
      <tr>
        <td><%= link_to event.name, event %></td>
        <td><%= event.date %></td>
        <td><%= event.location %></td>
        <td><%= event.state %></td>
        <td><%= event.user.first_name %></td>
        <td>
          <% if event.user.id == session[:user_id] %>
              <%= link_to "Edit", event %>
              <%= link_to "Delete", event, method: :delete %>
          <% else %>
              <% if is_user_joined_event? session[:user_id], event.id %>
                  Joining
                  <%= link_to "Cancel", is_user_joined_event?(event.id, session[:user_id]), method: :delete %>
              <% else %>
                  <%= link_to "Join", {:controller => "registrations", :action => "new", :event_id => event.id} %>
              <% end %>
          <% end %>
        </td>
      </tr>
  <% end %>
</table>
<h1>Add event</h1>

<% if flash[:event] %>
    <% @event=Event.new(flash[:event]) %>
<% end %>
<%= form_for @event do |e| %>
    <%= render 'shared/errors' %>
    <fieldset>
      <li class="required">
        <%= e.label :name %>
        <%= e.text_field :name %>
      </li>
      <li class="required">
        <%= e.label :date %>
        <%= e.date_field :date %>
      </li>
      <li class="required">
        <%= e.label :location %>
        <%= e.text_field :location %>
      </li>
      <li class="required">
        <%= e.label :state %>
        <%= e.select :state, ['AA', 'BB', 'CC'] %>
      </li>
      <p>
        <%= e.submit %>
      </p>
    </fieldset>
<% end %>

app/views/events/show.html.erb
<div id="left_div" style="float: left">
  <div id="event_info">
    <table>
      <tr>
        <td>Host:</td>
        <td><%= @event.user.first_name %></td>
      </tr>
      <tr>
        <td>Date:</td>
        <td><%= @event.date %></td>
      </tr>
      <tr>
        <td>Location:</td>
        <td><%= @event.location %>, <%= @event.state %></td>
      </tr>
      <tr>
        <td>People Who are joining the event</td>
        <td><%= @event.joined_users.size %></td>
      </tr>
    </table>
  </div>
  <br>
  <div id="event_attendees">
    <table>
      <tr>
        <th>Name</th>
        <th>Location</th>
        <th>State</th>
      </tr>
      <% @joined_users.each do |user|%>
          <tr>
            <td><%= user.first_name %></td>
            <td><%= user.location %></td>
            <td><%= user.state %></td>
          </tr>
      <% end%>
    </table>
  </div>
</div>
<div id="right_div" style="float: right">
  <h1>Discussion about the event</h1>
  <textarea name="disscussion" id="discussion" cols="80" rows="10">
    <%= @comment_string %>
  </textarea>
  <h1>Add Comment:</h1>
  <%= form_tag(comments_path) do %>
      <fieldset>
        <p>
          <%= text_area_tag :comment, nil, rows: 10, cols: 60 %>
        </p>
        <p>
          <%= hidden_field_tag :event_id, @event.id%>
        </p>
        <p>
          <%= submit_tag "Submit Comments" %>
        </p>
      </fieldset>
  <% end %>

</div>

app/views/home_page/index.html.erb
<h1>Register</h1>
<% if flash[:user] %>
    <% @user=User.new(flash[:user]) %>
<% end %>
<%= form_for @user, :url => {:controller => 'users', :action => 'create'} do |f| %>
    <%= render 'shared/errors' %>
    <fieldset>
      <li class="required">
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
      </li>
      <li class="required">
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
      </li>
      <li class="required">
        <%= f.label :location %>
        <%= f.text_field :location %>
      </li>
      <li class="required">
        <%= f.label :state %>
        <%= f.select :state, ['AA', 'BB', 'CC']%>
      </li>
      <li class="required">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </li>
      <li class="required">
        <%= f.label :password %>
        <%= f.text_field :password %>
      </li>
      <li class="required">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>
      </li>
      <p>
        <%= f.submit %>
      </p>
    </fieldset>
<% end %>
<h1>Login</h1>
<%= form_tag(session_path) do %>
    <fieldset>
      <p>
        <%= label_tag :email %>
        <%= email_field_tag :email, nil, autofocus: true %>
      </p>
      <p>
        <%= label_tag :password %>
        <%= password_field_tag :password, nil %>
      </p>
      <p>
        <%= submit_tag "Login" %>
      </p>
    </fieldset>
<% end %>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="header">
    <% if @event && !@event.new_record? %>
        <% if current_user %>
            <h1 style="float: left"><%= @event.name %></h1>
            <nav style="float: right">
              <p>
                <%= link_to "Edit my profile", current_user %>
                <%= link_to "Logout", session_path, method: :delete %>
              </p>
            </nav>
        <% else %>
            <h1 style="float: left">Welcome</h1>
        <% end %>
    <% else %>
        <% if current_user %>
            <h1 style="float: left">Welcome <%= current_user.first_name %></h1>
            <nav style="float: right">
              <p>
                <%= link_to "Event Dashboard", events_path %>
                <%= link_to "Logout", session_path, method: :delete %>
              </p>
            </nav>
        <% else %>
            <h1 style="float: left">Welcome</h1>
        <% end %>
    <% end %>

  </div>
</header>
<br style="clear: left">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeltReviewer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
  </head>

  <%= render 'layouts/header' %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:error] %>
    <section id="errors">
      <header>
        <h2>
          Oops! something wrong
        </h2>
        <h3>
          Please correct the following
          <%= pluralize(flash[:error_count], "error") %>
        </h3>
      </header>
      <ul>
        <% flash[:full_error_messages].each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </section>
<% end %>

app/views/users/index.html.erb
<header id="content-header">
  <h1><%= pluralize(@users.size, 'User') %></h1>
</header>
<ul id="users">
  <% @users.each do |user| %>
      <li><%= link_to user.first_name, user %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<article id="user">
  <%= form_for @user do |f| %>
      <%= render 'shared/errors' %>
      <fieldset>
        <li class="required">
          <%= f.label :first_name %>
          <%= f.text_field :first_name %>
        </li>
        <li class="required">
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
        </li>
        <li class="required">
          <%= f.label :location %>
          <%= f.text_field :location %>
        </li>
        <li class="required">
          <%= f.label :state %>
          <%= f.select :state, ['AA', 'BB', 'CC']%>
        </li>
        <li class="required">
          <%= f.label :email %>
          <%= f.text_field :email %>
        </li>
        <p>
          <%= f.submit %>
        </p>
      </fieldset>
  <% end %>
</article>